#!/usr/bin/env python3
# SPDX-License-Identifier: AGPL-3.0-or-later
#
# anatman — exocapitalist-audit skill helper.
#
# Emits a pre-populated Markdown audit template for one soul, organized by
# the Five Movements of exocapitalism (Scale, Fold, Lift, Drag, Last-Mile;
# Poliks & Trillo) and separately tracking Sadin's negative criterion.
# This helper only extracts what the soul declares; the reviewer fills in
# the judgment, residual-risk, and mitigation blocks.
#
# Usage:
#   python skills/exocapitalist-audit/helper.py souls/<name>.yaml
#   python skills/exocapitalist-audit/helper.py souls/<name>.yaml --write
"""Generate a pre-populated exocapitalist audit template for one soul."""

from __future__ import annotations

import argparse
import datetime as dt
import sys
from pathlib import Path

try:
    import yaml
except ImportError as exc:
    print(f"Missing dependency: {exc}. Install requirements.txt.", file=sys.stderr)
    sys.exit(2)


REPO_ROOT = Path(__file__).resolve().parents[2]
OUTPUT_DIR = REPO_ROOT / "docs" / "audits"

MOVEMENTS = [
    ("Scale", "scale_risk"),
    ("Fold", "fold_risk"),
    ("Lift", "lift_risk"),
    ("Drag", "drag_risk"),
    ("Last-Mile", "last_mile_risk"),
]


def load_yaml(path: Path) -> dict:
    with path.open("r", encoding="utf-8") as handle:
        return yaml.safe_load(handle) or {}


def get(data: dict, *path: str, default=None):
    cursor = data
    for key in path:
        if not isinstance(cursor, dict):
            return default
        cursor = cursor.get(key)
        if cursor is None:
            return default
    return cursor


def render(soul_path: Path) -> tuple[str, str]:
    soul = load_yaml(soul_path)
    name = get(soul, "meta", "name", default=soul_path.stem)
    version = get(soul, "meta", "version", default="unknown")
    today = dt.date.today().isoformat()

    lines: list[str] = []
    lines.append(f"# Exocapitalist audit: `{name}` ({today})")
    lines.append("")
    lines.append(f"- Soul file: `{soul_path.relative_to(REPO_ROOT)}`")
    lines.append(f"- Soul version: `{version}`")
    lines.append("- Five Movements source: Poliks & Trillo, *Exocapitalism*, 2025.")
    lines.append("- Negative criterion source: Sadin (distinct gate — see separate section below).")
    lines.append("")
    lines.append("> This template was generated by `skills/exocapitalist-audit/helper.py`.")
    lines.append("> Fill in every `<reviewer: …>` block before committing the report.")
    lines.append("")

    extraction = get(soul, "extraction_risk", default={}) or {}
    lines.append("## Five Movements")
    lines.append("")
    for label, key in MOVEMENTS:
        declared = extraction.get(key) or "(not declared by soul)"
        lines.append(f"### {label}")
        lines.append("")
        lines.append(f"**Soul declares:** {declared}")
        lines.append("")
        lines.append("**Reviewer assessment:**")
        lines.append("")
        lines.append("- <reviewer: independent reading of capture risk under this movement>")
        lines.append("")
        lines.append("**Mitigations:**")
        lines.append("")
        lines.append("- <reviewer: concrete, testable mitigation — not a restatement>")
        lines.append("")
        lines.append("**Residual risk:** <reviewer: HIGH / MEDIUM / LOW + one sentence>")
        lines.append("")

    kleshas = get(soul, "kleshas", "monitors", default=[]) or []
    lines.append("## Klesha monitors")
    lines.append("")
    for klesha in kleshas:
        lines.append(f"- `{klesha}`")
    if not kleshas:
        lines.append("- (none declared — flag as gap)")
    lines.append("")

    dependencies = get(soul, "negative_criterion", "dependencies_to_monitor", default=[]) or []
    declaration = get(soul, "negative_criterion", "declaration")
    lines.append("## Negative criterion (Sadin)")
    lines.append("")
    if declaration:
        lines.append(f"**Soul declares:** {declaration}")
        lines.append("")
    lines.append("**Dependencies to monitor:**")
    lines.append("")
    if dependencies:
        for dep in dependencies:
            lines.append(f"- `{dep}`")
    else:
        lines.append("- (none declared — flag as gap)")
    lines.append("")
    lines.append("**Gate verdict:** <reviewer: PASS / FAIL — does this soul intensify")
    lines.append("extraction, opacity, dependence, or decision capture?>")
    lines.append("")

    lines.append("## Overall recommendation")
    lines.append("")
    lines.append("- <reviewer: accept / accept-with-mitigations / reject, with rationale>")
    lines.append("")

    output_name = f"{soul_path.stem}_{today}.md"
    return "\n".join(lines), output_name


def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("soul", help="Path to the target soul YAML file")
    parser.add_argument(
        "--write",
        action="store_true",
        help=f"Write output to {OUTPUT_DIR.relative_to(REPO_ROOT)}/<soul>_<date>.md instead of stdout",
    )
    args = parser.parse_args()

    soul_path = Path(args.soul).resolve()
    if not soul_path.exists():
        print(f"Soul file not found: {soul_path}", file=sys.stderr)
        sys.exit(2)

    markdown, output_name = render(soul_path)

    if args.write:
        OUTPUT_DIR.mkdir(parents=True, exist_ok=True)
        output_path = OUTPUT_DIR / output_name
        output_path.write_text(markdown, encoding="utf-8")
        print(f"Wrote {output_path.relative_to(REPO_ROOT)}")
    else:
        sys.stdout.write(markdown)


if __name__ == "__main__":
    main()
